### PR TITLE
for slices with non-pointer struct element types, need to return pointer to element

### PR DESCRIPTION
**Pull request by rcoreilly**
Pointer is needed so that elements can be modified -- no other way to do this python-side, and generated code assumes pointer receivers.

This has been fully tested on my extensive codebase..

### CODE REVIEW

**Comment by rcoreilly** [comment]
I will have at least one more additional change to add to this set -- getting ready to more fully support python interface to our neural network simulator, so fixing various issues here.

**Comment by rcoreilly** [comment]
Ok, I think that's it for now -- have successfully converted a Go main program to run essentially identically in Python.

I also have a Go-to-Python converter program mostly working: https://github.com/goki/gotopy  -- it would be appropriate to host it here on go-python if you would be interested.  It might make sense to just give me write permission if so, so I can more efficiently contribute to managing both packages.

**Comment by sbinet** [comment]
done: you're an owner of `go-python` :)

**Comment by rcoreilly** [comment]
Great!  So do you want to review this PR or should I just merge it?

**Comment by sbinet** [comment]
go ahead.
I must admit I have less "free" time on my hands for `gopy` these days...

**Pull request merged**
