### PR TITLE
Split cffi py2 py3 tests

### PR DESCRIPTION
**Pull request by sbinet**
also make sure to (really) test the cffi+py3 mode.
add travis-CI with python3

### CODE REVIEW

**Comment by corona10** [comment]
@sbinet 
I recommend test multiple python version on Circle CI with a specific version of Go.

**Comment by sbinet** [comment]
PTAL

I got the weird segfault we had at some point while bringing `python2-cffi` into travis at some point (don't remember what we did to get rid of them.)

so I dropped python3-cffi from travis.
we'll revisit later.

wrt CircleCI: I don't have the spare cycles right now to investigate further but feel free to dab into this if you have time.

**Comment by corona10** [comment]
@sbinet 
That's weird. Except that, Everything looks great.
But can you explain what this error of Travis CI is?

````
2017/08/08 08:46:05 checking testbackend: "py3-cffi"...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'cffi'
````

**Comment by sbinet** [comment]
in commit `f2776b9` I removed `python3` (and the corresponding `python3-cffi` module) from the travis installation because of said weird segfaults (mentionned in https://github.com/go-python/gopy/pull/134#issuecomment-320896920)

that's the test telling us why the `"py3-cffi"` backend was discarded from the list of available tests.

**Comment by corona10** [comment]
@sbinet 
Okay Everything looks great 
LGTM!

**Pull request merged**
