### PR TITLE
add no-warn flag; use underlying type for Named types for struct fields; use overall package name for DecRef etc.

### PR DESCRIPTION
**Pull request by rcoreilly**
Fixes issues #219 #220 and #221

### CODE REVIEW

**Comment by sbinet** [comment]
LGTM.

- could you rebase your branch off the latest `master`? (this would remove a lot of noise from the PR)
- could you add a test for #220 
- could you add a test for #221 

thanks.

**Comment by rcoreilly** [comment]
I'm no git expert, so google told me to do this: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork -- I just tried replacing "merge" with rebase and it got stuck with conflicts rather quickly...

I will plan to just delete the original fork and start over with a new fork for the next time.  I looked at the diffs and they are correct so it should work.

I don't have time right now to do more with this so could you please just apply this PR and tests can be written later -- I'm preparing to teach online starting on Monday and this is part of the software I need to have available for my students, and I have a lot of other stuff to get done before then.  Thanks!

**Comment by cosnicolaou** [comment]
I can write the tests, just file an issue against me and I’ll take care of
it!


Cheers, Cos.

**Comment by sbinet** [comment]
closing this in favor of #224

**Pull request closed without merging**
